
# 1. LOAD LIBRARIES ------------------------------------------------------
library(CEMiTool)        # coexpression module detection
library(WGCNA)           # eigengene calculation & network utilities
library(igraph)          # graph/network objects
library(ggraph)          # graph plotting
library(ggplot2)         # general plotting
library(dplyr)           # data manipulation
library(tidyr)           # data reshaping (pivot_longer)
library(tibble)          # rownames_to_column
library(purrr)           # functional programming (walk, map)

library(clusterProfiler) # GO enrichment
library(enrichplot)      # enrichment visualization
library(rtracklayer)     # GFF import
library(ontologyIndex)   # GO ontology
library(viridis)  # color scales






# 2. LOAD EXPRESSION DATA -------------------------------
set.seed(123)

# 2.1 RLOG-normalized expression
data_path <- "perfiles_expresion_rlog.csv"
expr_rlog <- read.csv(data_path, sep = ",", row.names = "X")

# Remove sample metadata columns if present (adjust indices as needed)

# 2.2 Centered expression for profile plots
# The centered expression file was generated by subtracting the mean expression 
# of each gene (row-wise) across all samples, to highlight relative expression 
# changes between conditions. This transformation facilitates visualization of 
# expression profiles independently of absolute expression levels.
centered_path <- "perfiles_expresion_rlog_centrada.csv"
expr_centered <- read.csv(centered_path, sep = ",", row.names = "X")






# 3. CEMiTool MODULE DETECTION ------------------------------------------
cem_obj <- cemitool(expr_rlog, filter = FALSE)

# Gene–module mapping
genes_modules_df <- as.data.frame(module_genes(cem_obj))

# Inspect
print(cem_obj)
cat("Number of modules:", nmodules(cem_obj), "
")
head(genes_modules_df)

# Module sizes
module_size_df <- genes_modules_df %>%
  count(modules, name = "size") %>%
  arrange(modules)
print(module_size_df)




# 4. ADJACENCY MATRIX AND SOFT-THRESHOLDING -----------------------------
power_val <- 7
cem_obj <- get_adj(
  cem_obj,
  power_val,
  network_type = "unsigned",
  cor_function = "cor",
  cor_method = "pearson"
)
adj_matrix <- cem_obj@adjacency

# Scale-free topology plot
connectivity <- softConnectivity(t(expr_rlog), type = "unsigned", power = power_val,
                                  corFnc = "cor", corOptions = "use = 'p'")
scaleFreePlot(connectivity)



# 4.1 COMPUTE TOM AND DISSIMILARITY MATRIX --------------------------------
# Calculate Topological Overlap Matrix (TOM)
TOM <- TOMsimilarity(adj_matrix)
# Dissimilarity TOM
dissTOM <- 1 - TOM
# Save dissTOM for downstream network plots
write.csv(dissTOM, "dissTOM.csv", quote = FALSE)








# 5. MODULE EIGENEGENES AND TRAIT CORRELATION ---------------------------
traits_path <- "traits.csv"
traits_df <- read.csv(traits_path, sep = ",", row.names = 1)

# Prepare colors vector for WGCNA
gene_colors <- setNames(genes_modules_df$modules, genes_modules_df$genes)

# Calculate eigengenes
MEs_raw <- moduleEigengenes(t(expr_rlog), colors = gene_colors)$eigengenes
MEs <- orderMEs(MEs_raw)

# Select modules ME M1–M13
module_order <- paste0("ME", paste0("M", 1:13))
MEs_filtered <- MEs[, intersect(module_order, colnames(MEs))]

# Correlation with traits
nSamples <- ncol(expr_rlog)
modTraitCor <- cor(MEs_filtered, traits_df, use = "pairwise.complete.obs")
modTraitPval <- corPvalueStudent(modTraitCor, nSamples)

# Heatmap
text_matrix <- matrix(paste0(signif(modTraitCor, 2),"\n(",signif(modTraitPval,1),")"),
                      nrow = nrow(modTraitCor), ncol = ncol(modTraitCor))
rownames(text_matrix) <- rownames(modTraitCor)
colnames(text_matrix) <- colnames(modTraitCor)

png("all_modules_trait_relationships.png", width = 2000, height = 2000, res = 300)
labeledHeatmap(
  Matrix = modTraitCor,
  xLabels = colnames(modTraitCor),
  yLabels = rownames(modTraitCor),
  textMatrix = text_matrix,
  colors = blueWhiteRed(50),
  main = "Module–Trait Relationships"
)
dev.off()











# 6. EXPRESSION PROFILE PLOTS -------------------------------------------
exp_long <- expr_centered %>%
  tibble::rownames_to_column("genes") %>%
  pivot_longer(-genes, names_to = "sample", values_to = "expression") %>%
  inner_join(genes_modules_df, by = "genes")

sample_order <- colnames(expr_centered)
group_ranges <- data.frame(
  group = c("epi", "meta", "amas", "trypo"),
  xmin  = c(1,    5,      6,     12),
  xmax  = c(4,    5,     11,     12),
  color = c("#c4e6a8", "#b8e1f2", "#f3c9c8", "#d2c4f2")
)






# 7. POSITIVE/NEGATIVE CORRELATION SEPARATION --------------------------
# Compute gene-module correlation as antes
library(stringr)
expr_mat <- t(expr_centered)
gene_corr_df <- tibble(
  genes   = colnames(expr_mat),
  modules = gene_colors[colnames(expr_mat)],
  cor     = NA_real_
)
for(m in unique(gene_corr_df$modules)) {
  eig            <- MEs[, paste0("ME", m)]
  genes_in_mod   <- gene_corr_df$genes[gene_corr_df$modules == m]
  gene_corr_df$cor[gene_corr_df$modules == m] <-
    cor(expr_mat[, genes_in_mod], eig, use = "pairwise.complete.obs")
}
gene_corr_df <- gene_corr_df %>%
  mutate(
    submod = case_when(
      cor <  0 ~ paste0(modules, "a"),
      cor >  0 ~ paste0(modules, "b"),
      TRUE     ~ paste0(modules, "0")
    )
  )

modulos_ab <- gene_corr_df %>%
  select(genes, modules, submod = submod) %>%
  mutate(
    modules = paste0("M", modules),  # asegurar que los nombres sean como M1, M2...
    modules = str_replace(modules, "MM", "M"),  # en caso de que ya esté bien, esto no cambia nada
    modules = str_replace(modules, "A$", "_neg"),  # renombra A como _neg
    modules = str_replace(modules, "B$", "_pos")   # renombra B como _pos
  )

# Map replicates to stages
sample_order <- c(
  "E7","E14","E21","E28",   # epi
  "M",                       # meta
  "A4","A6","A12","A24",     # amas
  "A48","A72",               # amas extended
  "T"                        # trypo
)

combined_df <- exp_long %>%
  mutate(
    stage = sample %>%
      str_remove("_R[0-9]+$") %>%
      str_replace_all(c(
        "^Epi_7dias$"   = "E7",
        "^Epi_14dias$"  = "E14",
        "^Epi_21dias$"  = "E21",
        "^Epi_28dias$"  = "E28",
        "^Meta_1$"      = "M",
        "^Amas_4h$"     = "A4",
        "^Amas_6h$"     = "A6",
        "^Amas_12h$"    = "A12",
        "^Amas_24h$"    = "A24",
        "^Amas_48h$"    = "A48",
        "^Amas_72h$"    = "A72",
        "^Trypo$"       = "T"
      ))
  ) %>%
  left_join(gene_corr_df, by = c("genes","modules"))

# Create outdirs
dir.create("plots_profiles_segmented", showWarnings = FALSE)
dir.create("genes_by_module_correlation", showWarnings = FALSE)


plot_profile <- function(data, title, color_line) {
  # Average per stage
  avg <- data %>%
    group_by(stage) %>%
    summarise(mean_expr = mean(expression), .groups = "drop")
  
  data$stage <- factor(data$stage, levels = sample_order)
  avg$stage  <- factor(avg$stage,  levels = sample_order)
  
  ggplot() +
    
    purrr::pmap(
      list(group_ranges$xmin, group_ranges$xmax, group_ranges$color),
      function(xmin, xmax, col) annotate(
        "rect",
        xmin = xmin - 0.5, xmax = xmax + 0.5,
        ymin = -Inf, ymax = Inf,
        fill = col, alpha = 0.5
      )
    ) +
    geom_line(
      data = data,
      aes(x = stage, y = expression, group = genes),
      color = color_line, alpha = 0.4
    ) +
    geom_line(
      data = avg,
      aes(x = stage, y = mean_expr, group = 1),
      color = "black", size = 0.8
    ) +
    labs(title = title, x = "Stage", y = "Centered expression") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}


for(mod in unique(gene_corr_df$modules)) {
  df_sub <- combined_df %>% filter(modules == mod)
  pos    <- df_sub %>% filter(cor > 0)
  neg    <- df_sub %>% filter(cor < 0)
  
  # Save genes
  writeLines(unique(pos$genes),
             paste0("genes_by_module_correlation/", mod, "_B.txt"))
  writeLines(unique(neg$genes),
             paste0("genes_by_module_correlation/", mod, "_A.txt"))
  
  # Plots
  if(nrow(pos) > 0) {
    p_pos <- plot_profile(pos, paste("Module", mod, "(Positive)"), "red")
    ggsave(paste0("plots_profiles_segmented/module_", mod, "_B.png"),
           p_pos, width = 10, height = 6, dpi = 300)
  }
  if(nrow(neg) > 0) {
    p_neg <- plot_profile(neg, paste("Module", mod, "(Negative)"), "red")
    ggsave(paste0("plots_profiles_segmented/module_", mod, "_A.png"),
           p_neg, width = 10, height = 6, dpi = 300)
  }
}







# 8. GO ENRICHMENT FOR POSITIVE/NEGATIVE MODULES --------------------------
# Split modules by positive/negative correlation and run GO enrichment
# Requires gene2go_df and go_names_df from earlier setup

files <- list.files("genes_by_module_correlation", pattern = "\\.txt$", full.names = TRUE)

# GO annotations
GOs <- read.csv("TriTrypDB-54_TcruziCLBrenerEsmeraldo-like_GO.gaf", sep = "\t", header = FALSE)
go_obo <- get_ontology("http://purl.obolibrary.org/obo/go.obo", extract_tags = "everything")
go_terms <- data.frame(go_id = go_obo$id, name = go_obo$name, definition = go_obo$def, stringsAsFactors = FALSE)
GOs <- merge(GOs, go_terms, by.x = "V5", by.y = "go_id", all.x = TRUE)

gene2go_df <- GOs %>%
  select(gene_id = V2, go_id = V5) %>%
  distinct() %>%
  select(go_id, gene_id)

go_names_df <- GOs %>%
  select(go_id = V5, term_name = name) %>%
  distinct()

for(file in files) {
  fname <- basename(file)
  parts <- strsplit(fname, "_")[[1]]
  mod <- parts[1]
  sign <- sub("\\.txt$", "", parts[2])  # 'positive' or 'negative'
  
  genes <- readLines(file)
  if(length(genes) == 0) next
  
  ego <- tryCatch(
    enricher(
      gene = genes,
      TERM2GENE = gene2go_df,
      TERM2NAME = go_names_df,
      pAdjustMethod = "BH",
      pvalueCutoff = 0.05,
      qvalueCutoff = 0.05
    ),
    error = function(e) NULL
  )
  if(is.null(ego) || nrow(ego@result) == 0) {
    cat("No significant GO enrichment for module", mod, "sign", sign, "
")
    next
  }
  
  outdir <- file.path("results_GO_ab", paste0(mod, "_", sign))
  dir.create(outdir, showWarnings = FALSE)
  
  # Dotplot
  try({
    dp <- dotplot(ego, showCategory = 20, title = paste("GO Enrichment -", mod, sign)) +
      scale_color_viridis(option = "D", direction = -1, name = "-log10(FDR)") +
      theme_minimal(base_size = 12)
    ggsave(file.path(outdir, paste0("dotplot_", mod, "_", sign, ".png")), dp,
           width = 6, height = 8, dpi = 300)
  }, silent = TRUE)
}
 
 




 

#### 9. STACKED BARPLOT FOR GENE FAMILIES IN MODULES M4/M5/M13 (A/B) ##########

# Load gene annotations from GFF file
library(ape)
library(stringr)

# Load GFF and keep only protein-coding genes
gff_path <- 'TriTrypDB-54_TcruziCLBrenerEsmeraldo-like.gff'
tc_gff <- read.gff(gff_path)  # manually remove initial ## lines if needed
tc_gff <- tc_gff[tc_gff$type == 'protein_coding_gene', ]

# Extract gene ID and description from the attributes column
attributes_df <- as.data.frame(tc_gff$attributes)
attributes_df <- as.data.frame(str_split_fixed(attributes_df$`tc_gff$attributes`, ";", 2))
attributes_df$V1 <- gsub("\\ID=", "", attributes_df$V1)
attributes_df$V2 <- gsub(".*=", "", attributes_df$V2)
attributes_df$V3 <- NA

annotations <- attributes_df
colnames(annotations) <- c('gene_id', 'description', 'V3')

# 9.1 Classify families and create full data table
stack_df_full <- modulos_ab %>%
  mutate(
    modules = str_replace(modules, "_neg$", "A"),
    modules = str_replace(modules, "_pos$", "B"),
    submod = str_replace_all(submod, c("MM4a" = "M4A", "MM4b" = "M4B",
                                       "MM5a" = "M5A", "MM5b" = "M5B",
                                       "MM13a" = "M13A", "MM13b" = "M13B"))
  ) %>%
  filter(submod %in% c("M4A", "M4B", "M5A", "M5B", "M13A", "M13B")) %>%
  inner_join(annotations, by = c("genes" = "gene_id")) %>%
  rowwise() %>%
  mutate(family = case_when(
    genes %in% translation_genes ~ "Translation",
    str_detect(description, regex(paste(patterns$trans_sialidase, collapse = "|"), ignore_case = TRUE)) ~ "Trans-sialidases",
    str_detect(description, regex(paste(patterns$masp, collapse = "|"), ignore_case = TRUE)) ~ "MASPs",
    str_detect(description, regex(paste(patterns$mucin, collapse = "|"), ignore_case = TRUE)) &
      !str_detect(description, regex(paste(patterns$masp, collapse = "|"), ignore_case = TRUE)) ~ "Mucins",
    str_detect(description, regex(paste(patterns$dgf1, collapse = "|"), ignore_case = TRUE)) ~ "DGF1",
    str_detect(description, regex(paste(patterns$rhs, collapse = "|"), ignore_case = TRUE)) ~ "RHS",
    str_detect(description, regex(paste(patterns$gp63, collapse = "|"), ignore_case = TRUE)) ~ "GP63",
    str_detect(description, regex("^hypothetical protein$", ignore_case = TRUE)) ~ "Hypothetical",
    TRUE ~ "Other"
  )) %>%
  ungroup()

# 9.2 Aggregate data for barplot
stack_df <- stack_df_full %>%
  count(submod, family) %>%
  group_by(submod) %>%
  mutate(perc = n / sum(n) * 100) %>%
  ungroup() %>%
  mutate(
    submod = factor(submod, levels = c("M4A", "M4B", "M5A", "M5B", "M13A", "M13B")),
    family = factor(family, levels = c("Trans-sialidases", "MASPs", "Mucins", "DGF1", "RHS", "GP63", "Translation", "Hypothetical", "Other"))
  )

# 9.3 Define manual colors
manual_colors <- c(
  "Trans-sialidases" = "#E41A1C",
  "MASPs"            = "#377EB8",
  "Mucins"           = "#4DAF4A",
  "DGF1"             = "#984EA3",
  "RHS"              = "#FF7F00",
  "GP63"             = "#A65628",
  "Translation"      = "#FFD700",
  "Hypothetical"     = "darkgrey",
  "Other"            = "lightgrey"
)

# 9.4 Plot and save barplot
p_bar <- ggplot(stack_df, aes(x = submod, y = perc, fill = family)) +
  geom_col(width = 0.7) +
  scale_fill_manual(values = manual_colors) +
  labs(x = "Module subset", y = "% of genes", fill = "Family") +
  theme_minimal(base_size = 14) +
  theme(axis.title = element_text(face = "bold"),
        legend.position = "right")

ggsave("stacked_barplot_M4_M5_M13_AB.png", p_bar, width = 8, height = 6, dpi = 500)




# 10. GO enrichment on “Other” genes per module
library(clusterProfiler)
subsets <- c('M4A', 'M4B', 'M5A', 'M5B', 'M13A', 'M13B')
for (mod in subsets) {
  genes_for_enrichment <- stack_df_full %>%
    filter(submod == mod, family %in% c("Other", "Translation")) %>%
    filter(!str_detect(tolower(description), "hypothetical")) %>%
    pull(genes)
  
  if (length(genes_for_enrichment) < 5) {
    message(paste("Skipping module", mod, "- too few genes for enrichment"))
    next
  }
  
  ego <- enricher(
    gene          = genes_for_enrichment,
    TERM2GENE     = gene2go_df,
    TERM2NAME     = go_names_df,
    pAdjustMethod = "BH",
    pvalueCutoff  = 0.1,
    qvalueCutoff  = 0.1
  )
  
  if (!is.null(ego) && nrow(ego@result) > 0) {
    # Filter to terms with at least 2 genes annotated (Count column)
    ego@result <- ego@result[ego@result$Count >= 2, ]
    
    if (nrow(ego@result) > 0) {
      tryCatch({
        dp <- dotplot(ego,
                      showCategory = min(20, nrow(ego@result)),
                      title = paste("GO Enrichment – Other and Translation (", mod, ")", sep = "")) +
          theme_minimal(base_size = 12)
        
        ggsave(filename = paste0("dotplot_GO_Other_Translation_", mod, ".png"),
               plot = dp,
               width = 6,
               height = 8,
               dpi = 300)
        
        message(paste("GO plot saved for module", mod))
      }, error = function(e) {
        message(paste("Error plotting module", mod, ":", e$message))
      })
    } else {
      message(paste("No GO terms with >= 2 genes for module", mod))
    }
  } else {
    message(paste("No significant enrichment found for module", mod))
  }
}


























# 11. GRAPH OF HUB GENES (DISSIMILARITY NETWORK) -----------------------
library(igraph)
library(ggraph)
library(ggplot2)
library(tidygraph)


# Extract hub genes per module
# Number of hubs to extract per module
n <- 5
# Retrieve all hub genes from the CEMiTool object
hubs <- get_hubs(cem_obj, n)
# Extract hubs for modules M1 to M13 and store them in a list
modules <- paste0("M", 1:13)
hubs_by_module <- lapply(modules, function(mod) {
  hubs[[mod]]
})
# Name each list element with the corresponding module
names(hubs_by_module) <- modules
# Combine all hubs into a single data frame for export
hubs_df <- do.call(rbind, lapply(names(hubs_by_module), function(mod) {
  data.frame(module = mod, gene = hubs_by_module[[mod]])
}))
# Save to CSV file
write.csv(hubs_df, "hubs_by_module.csv", row.names = FALSE)







# Read hub gene list
genes_deseados <- readLines("top650_hubgenes.txt") # from sup table 2
cat("Number of hub genes:", length(genes_deseados), "
")

# Assign gene names as row and column names
dissTOM <- as.data.frame(dissTOM)
#dissTOM <- dissTOM[, -1]

gene_names <- rownames(adj_matrix)
rownames(dissTOM) <- gene_names
colnames(dissTOM) <- gene_names


# Subset to hub genes
submatrix <- dissTOM[genes_deseados, genes_deseados]
adj_matrix <- 1 - submatrix
adj_matrix[adj_matrix < 0.1] <- 0  # filter weak connections

# Graph
graph_hub <- graph_from_adjacency_matrix(as.matrix(adj_matrix), mode = "undirected", weighted = TRUE)

V(graph_hub)$name <- rownames(adj_matrix)


modules <- genes_modules_df %>% filter(genes %in% V(graph_hub)$name)


V(graph_hub)$module <- modules$modules[match(V(graph_hub)$name, modules$genes)]


colores_pastel <- c("#FFB3BA", "#FFDFBA", "#FFFFBA", "#BAFFC9", "#BAE1FF",
                    "#D1C4E9", "#FFCCBC", "#E6EE9C", "#FFAB91", "#CE93D8",
                    "#81D4FA", "#A5D6A7", "#FFE082")
module_names <- sprintf("M%d", 1:13)
mod_colors <- setNames(colores_pastel, module_names)

# Assign colors to moduls
V(graph_hub)$color <- mod_colors[as.character(V(graph_hub)$module)]

# Plot. Change setting for layout
p <- ggraph(graph_hub, layout = "fr") +
  geom_edge_link(aes(width = weight), alpha = 0.002) +
  geom_node_point(aes(color = factor(module)), size = 3) +
  scale_color_manual(values = mod_colors) +
  theme_void() +
  ggtitle("Hub Gene Network")

# Guardar
ggsave("graph_genes.png", plot = p, width = 10, height = 8, dpi = 300)





# 12. SUBNETWORK WITHOUT GENE ANNOTATIONS -------------------------------
# Rebuild with same adjacency
graph_full <- graph_hub
# Add full gene label
V(graph_full)$label_full <- V(graph_full)$name

# Subnetwork around a gene of interest
gen_interes <- "TcCLB.511693.70"  # modify as needed
if(!(gen_interes %in% V(graph_full)$name)) stop("Gene of interest not in network")
mod_interes <- V(graph_full)$module[V(graph_full)$name == gen_interes]
neighs <- neighbors(graph_full, gen_interes)
neighs_same <- neighs[V(graph_full)$module[neighs] == mod_interes]
if(length(neighs_same)==0) stop("No neighbors in same module")

# Compute top N neighbors by weight
weights <- sapply(neighs_same, function(v) E(graph_full)[gen_interes %--% v]$weight)
df_nb <- data.frame(gene = V(graph_full)$name[neighs_same], weight = weights)
topN <- head(df_nb[order(-df_nb$weight), ], 11)
nodes_sub <- c(gen_interes, topN$gene)
subg <- induced_subgraph(graph_full, vids = nodes_sub)
V(subg)$node_color <- ifelse(V(subg)$name==gen_interes, "red", mod_colors[V(subg)$module])

sub_plot <- ggraph(subg, layout = "fr") +
  geom_edge_link(aes(width = weight), alpha = 0.1) +
  geom_node_point(aes(color = node_color), size = 5) +
  geom_node_text(aes(label = label_full), repel = TRUE, size = 6) +
  scale_color_identity(guide = "none") +
  theme_minimal() + theme(
    panel.grid = element_blank(), axis.title=element_blank(),
    axis.text=element_blank(), axis.ticks=element_blank(),
    plot.title = element_text(size=16, face="bold")
  ) +
  ggtitle(paste("Subnetwork of", gen_interes, "Module", mod_interes))

ggsave(paste0("subgraph_", gen_interes, "_", mod_interes, ".png"), plot = sub_plot, width = 8, height = 6, dpi = 300)














# 13 SAVE NEIGHBORS FOR HYPOTHETICAL HUB GENES ------------------------
# List of genes of interest
genes_interes <- c(
  "TcCLB.510849.30", "TcCLB.508835.10", "TcCLB.506113.80", "TcCLB.510275.272",
  "TcCLB.509233.10", "TcCLB.508771.50", "TcCLB.509157.220", "TcCLB.508731.40",
  "TcCLB.510347.29", "TcCLB.506927.20", "TcCLB.503811.45", "TcCLB.511623.20",
  "TcCLB.511127.90", "TcCLB.503903.70", "TcCLB.453917.9", "TcCLB.511693.70"
)


dir.create("neighbors", showWarnings = FALSE)

for(gen in genes_interes){
  if(!(gen %in% V(graph_full)$name)) { 
    warning(paste(gen, "not in network")) 
    next 
  }
  
  neighs <- neighbors(graph_full, gen)
  same_mod <- neighs[V(graph_full)$module[neighs] == V(graph_full)$module[V(graph_full)$name == gen]]
  
  if(length(same_mod) == 0){ 
    warning(paste(gen, "no same-module neighbors")) 
    next 
  }
  
  weights <- sapply(same_mod, function(v) E(graph_full)[gen %--% v]$weight)
  
  df_nb <- data.frame(gene_id = V(graph_full)$name[same_mod], weight = weights)
  df_top <- head(df_nb[order(-df_nb$weight), ], 11)
  df_out <- bind_rows(data.frame(gene_id = gen, weight = NA), df_top)
  
  write.csv(df_out, file = paste0("neighbors/", gen, ".csv"), row.names = FALSE)
}










 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 







